# Generated by Django 4.0.4 on 2022-10-21 16:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_alter_profile_previous_work_alter_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='previous_work',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
