# Generated by Django 4.0.4 on 2022-10-22 11:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_alter_profile_previous_work_alter_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
